version: "0.1"
user: mayankmaurya
key: vb2QB3komcYoPqlEXN2hHGd33aok6SOZFQA9tUPl8erAiOmw82
testSuites: []
pre: [npm install, npm install cypress --save-dev, npm install lambdatest-cypress-cli@3.0.30 --npm-force=true]
preDirectives:
    commands: [npm install, npm install cypress --save-dev, npm install lambdatest-cypress-cli@3.0.30 --npm-force=true]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
post: [cat yaml/win/.hyperexecute_autosplit.yaml]
postDirectives:
    commands: [cat yaml/win/.hyperexecute_autosplit.yaml]
    shell: ""
    workingDirectory: ""
env:
    CYPRESS_CACHE_FOLDER: cypressCache
jobLabel:
    - cypress-v10
    - win
    - autosplit
runson: win
autosplit: true
concurrency: 1
testDiscovery:
    command: ls cypress/e2e/2-advanced-examples
    mode: static
    type: raw
testDiscoveryResult:
    - action.cy.js
testDiscoveryResult2D:
    - - action.cy.js
testRunnerCommand: npx cypress run  --spec ./cypress/e2e/2-advanced-examples/$test --browser=chrome-95.0 --headed --config video=false
globalTimeout: 90
tunnelOpts:
    testsPerTunnel: 10
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
    - node_modules
    - cypressCache
cacheKey: '{{ checksum "package.json" }}'
retryOnFailure: true
maxRetries: 1
jobID: 655ab811-925b-419e-a78b-099e1472765f
codeDirectory: hyperexecute-cypress-v10-sample
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: false
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: true
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypressOps:
    Build: Hyperexecute Cypress Sample Build-accessibility
    BuildTags:
        - Hyperexecute-Cypress
    Tags:
        - Hyperexecute
        - Cypress
        - Windows
        - Autosplit
    accessibility: true
    accessibilityBestPractice: false
    accessibilityNeedsReview: true
    accessibilityWcagVersion: wcag21a
cypress: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: false
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: ""
    name: ""
    type: default
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
