---
version: 0.1
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
retryOnFailure: true
runson: win
cypress: true
maxRetries: 1
concurrency: 2
autosplit: true
pre:
  - npm install
  - npm install cypress --save-dev
  - npm install lambdatest-cypress-cli@3.0.30 --npm-force=true
cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules
  - cypressCache
env:
  CYPRESS_CACHE_FOLDER: cypressCache
testDiscovery:
  mode: static
  type: raw
  command: ls cypress/e2e/2-advanced-examples
testRunnerCommand: npx cypress run  --spec ./cypress/e2e/2-advanced-examples/$test --browser=chrome-95.0 --headed --config video=false
cypressOps:
 Build: "Hyperexecute Cypress Sample Build-accessibility"
 Tags: ["Hyperexecute","Cypress", "Windows", "Autosplit"]
 BuildTags: ["Hyperexecute-Cypress"]
 accessibility: true
 accessibilityWcagVersion: "wcag21a"
 accessibilityBestPractice: false  
 accessibilityNeedsReview: true
post:
  - cat yaml/win/.hyperexecute_autosplit.yaml



jobLabel: [cypress-v10, win, autosplit]